"""Weekly report generator for Token Cop.

Generates a markdown or JSON summary of LLM token usage for Slack/email.

Usage:
    python -m scripts.generate_report --period weekly --format markdown
    python -m scripts.generate_report --period monthly --format json
"""

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone

from dashboard.data import (
    fetch_all_provider_data,
    fetch_audit_data,
    compute_smart_token_score,
    get_model_mix,
    get_cost_trend,
)


def generate_report(period: str = "weekly", fmt: str = "markdown") -> str:
    """Generate a usage report for the specified period."""
    now = datetime.now(timezone.utc)
    days = 7 if period == "weekly" else 30

    end_date = now.strftime("%Y-%m-%d")
    start_date = (now - timedelta(days=days)).strftime("%Y-%m-%d")
    prev_start = (now - timedelta(days=days * 2)).strftime("%Y-%m-%d")
    prev_end = start_date

    # Fetch data
    data = fetch_all_provider_data(start_date, end_date)
    prev_data = fetch_all_provider_data(prev_start, prev_end)
    audit = fetch_audit_data(days)

    totals = data.get("totals", {})
    model_mix = get_model_mix(data)
    trend = get_cost_trend(data, prev_data)
    smart_score = compute_smart_token_score(data)

    grade = "N/A"
    overall_score = 0
    recommendations = []
    scores = {}
    if audit:
        grade = audit.get("overall_grade", "N/A")
        overall_score = audit.get("overall_score", 0)
        recommendations = audit.get("recommendations", [])
        scores = audit.get("scores", {})

    if fmt == "json":
        return _generate_json(
            period, start_date, end_date, totals, model_mix, trend,
            grade, overall_score, smart_score, recommendations, scores,
        )
    else:
        return _generate_markdown(
            period, start_date, end_date, days, totals, model_mix, trend,
            grade, overall_score, smart_score, recommendations, scores,
        )


def _generate_markdown(
    period, start_date, end_date, days, totals, model_mix, trend,
    grade, overall_score, smart_score, recommendations, scores,
) -> str:
    """Generate markdown report."""
    # Determine week label
    start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    period_label = "Weekly" if period == "weekly" else "Monthly"
    date_label = start_dt.strftime("%B %d, %Y")

    total_cost = totals.get("total_cost_usd", 0)
    total_requests = totals.get("total_requests", 0)
    daily_avg = total_cost / days if days > 0 else 0
    cpr = total_cost / total_requests if total_requests > 0 else 0
    cpr_change = trend.get("cpr_change_pct", 0)
    cpr_arrow = "\u2193" if cpr_change < 0 else ("\u2191" if cpr_change > 0 else "\u2194")

    lines = [
        f"# Token Cop {period_label} Report -- Week of {date_label}",
        "",
        f"## Efficiency Grade: {grade} ({overall_score}/10)",
        "",
        "### Spend Summary",
        f"- **Total**: ${total_cost:,.2f} across {total_requests:,} requests",
        f"- **Daily average**: ${daily_avg:,.2f}",
        f"- **Cost per request**: ${cpr:.4f} ({cpr_arrow} {abs(cpr_change):.0f}% vs last {period})",
        f"- **Smart Token Score**: {smart_score}",
        "",
    ]

    # Model mix table
    if model_mix:
        lines.append("### Model Mix")
        lines.append("| Model | Requests | Cost | % of Total |")
        lines.append("|-------|----------|------|------------|")
        for m in model_mix[:10]:
            lines.append(
                f"| {m['model']} | {m['requests']:,} | ${m['cost']:.2f} | {m['percentage']:.0f}% |"
            )
        lines.append("")

    # Wins from trend data
    wins = _find_wins(scores, trend, totals)
    if wins:
        lines.append("### Top Wins This Period")
        for i, win in enumerate(wins[:3], 1):
            lines.append(f"{i}. {win}")
        lines.append("")

    # Recommendations
    if recommendations:
        lines.append("### Top Recommendations")
        for i, rec in enumerate(recommendations[:3], 1):
            lines.append(f"{i}. **{rec}**")
        lines.append("")

    lines.extend([
        "---",
        "*Generated by Token Cop | More tokens is FINE -- they need to be SMART tokens.*",
    ])

    return "\n".join(lines)


def _generate_json(
    period, start_date, end_date, totals, model_mix, trend,
    grade, overall_score, smart_score, recommendations, scores,
) -> str:
    """Generate JSON report."""
    return json.dumps({
        "report_type": period,
        "start_date": start_date,
        "end_date": end_date,
        "efficiency_grade": grade,
        "overall_score": overall_score,
        "smart_token_score": smart_score,
        "totals": totals,
        "model_mix": model_mix,
        "trend": trend,
        "recommendations": recommendations,
        "scores": {
            k: v for k, v in scores.items() if k != "top_savings"
        },
    }, indent=2)


def _find_wins(scores: dict, trend: dict, totals: dict) -> list[str]:
    """Extract positive highlights from audit scores and trend data."""
    wins = []

    cache = scores.get("cache_utilization", {})
    if cache.get("score", 0) >= 7:
        wins.append(f"Cache utilization is strong: {cache.get('detail', '')}")

    if trend.get("cpr_change_pct", 0) < -5:
        wins.append(
            f"Cost per request down {abs(trend['cpr_change_pct']):.0f}% vs previous period"
        )

    mix = scores.get("model_mix", {})
    if mix.get("score", 0) >= 7:
        wins.append(f"Good model distribution: {mix.get('detail', '')}")

    doc = scores.get("document_ingestion", {})
    if doc.get("score", 0) >= 7:
        wins.append(f"Healthy input/output ratio: {doc.get('detail', '')}")

    total_cache = totals.get("cache_read_tokens", 0)
    total_input = totals.get("input_tokens", 0)
    if total_input > 0:
        cache_pct = total_cache / total_input * 100
        if cache_pct > 15:
            wins.append(f"Cache hit rate at {cache_pct:.0f}%")

    return wins


def main():
    parser = argparse.ArgumentParser(description="Generate Token Cop usage report")
    parser.add_argument(
        "--period",
        choices=["weekly", "monthly"],
        default="weekly",
        help="Report period (default: weekly)",
    )
    parser.add_argument(
        "--format",
        choices=["markdown", "json"],
        default="markdown",
        dest="fmt",
        help="Output format (default: markdown)",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output file path (default: stdout)",
    )

    args = parser.parse_args()
    report = generate_report(period=args.period, fmt=args.fmt)

    if args.output:
        with open(args.output, "w") as f:
            f.write(report)
        print(f"Report written to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
